FROM amazoncorretto:latest

RUN amazon-linux-extras install epel -y
RUN yum update -y && \
	yum install wget -y
RUN yum install jenkins java-1.8.0-openjdk-devel -y
RUN wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo && \
	rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
RUN yum install jenkins -y


EXPOSE 8080

ENTRYPOINT ["java"]
CMD ["-jar","/usr/lib/jenkins/jenkins.war"]
