FROM ubuntu:latest

RUN apt-get update && \
apt-get install wget -y && \
apt-get install gnupg -y
RUN wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | apt-key add -
RUN echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list

RUN apt-get update && \
    apt-get install -y jenkins

RUN apt search openjdk && \
    apt install openjdk-11-jdk -y

EXPOSE 8080

ENTRYPOINT ["java"]
CMD ["-jar", "/usr/share/jenkins/jenkins.war"]